scrape_configs:
- job_name: prometheus
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
- job_name: zb
  scrape_interval: 1s
  metrics_path: /zeebe.prom
  scheme: http
  static_configs:
  - targets:
    ##### Specify YOUR AWS public DNS names of your brokers here, easist is just to copy them from ansible
    - ec2-18-184-79-69.eu-central-1.compute.amazonaws.com
    - ec2-35-159-10-212.eu-central-1.compute.amazonaws.com
    - ec2-52-59-37-169.eu-central-1.compute.amazonaws.com
    - ec2-54-93-38-92.eu-central-1.compute.amazonaws.com