---
- name: Download the Go tarball
  get_url:
    url: "{{ go_download_location }}"
    dest: /tmp/{{ go_tarball }}

- name: Register the current Go version (if any)
  command: /tmp/go/bin/go version
  ignore_errors: yes
  register: go_version
  changed_when: false

- name: Remove old installation of Go
  file:
    path: /tmp/go
    state: absent
  when: go_version is failed or go_version.stdout != go_version_target

- name: Extract the Go tarball if Go is not yet installed or not the desired version
  unarchive:
    src: /tmp/{{ go_tarball }}
    dest: /tmp/
    copy: no
  when: go_version is failed or go_version.stdout != go_version_target


- name: Add the Go bin directory to the PATH environment variable for all users
  become: yes
  copy:
    src: go-bin.sh
    dest: /etc/profile.d/go-bin.sh

- name: Set GOPATH for all users
  become: yes
  copy:
    src: go-path.sh
    dest: /etc/profile.d/go-path.sh
  when: set_go_path
